[package]
name = "forms_system"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
once_cell = "1.19.0"
poem="3.1.0"
sqlx = "0.8.2"
tera = "1.20.0"
tokio = { version = "1.40.0", features = ["rt-multi-thread", "macros"] }
